project:
  type: website

website:
  title: "Ian Zhang"
  navbar:
    left:
      - href: index.qmd
        text: Landing Page
      - href: about.qmd
        text: About Page

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

